# Site settings
title: "Steven Wade Jr"
description: > # this means to ignore newlines until "email:"
   Digital Developer, Pretty Awesome Dude
email: stevenwadejr@gmail.com
baseurl: ""
url: "http://stevenwadejr.com"
permalink: pretty

#Build Settings
markdown: kramdown
highlighter: rouge
paginate:   5

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate

# Content Settings
logo: "/assets/images/author.jpg"
cover: "/assets/images/44a0e76eb1cf11e28bf722000a1f92f7_7.jpg"

name: 'Steven Wade'
author: 'Steven Wade'
author_image: "/assets/images/author.jpg"

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/stevenwadejr
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/stevenwadejr
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
