# Site settings
title: "Steven Wade Jr"
description: > # this means to ignore newlines until "email:"
   Digital Developer, Pretty Awesome Dude
email: stevenwadejr@gmail.com
baseurl: ""
url: "http://stevenwadejr.com"
permalink: pretty

#Build Settings
markdown: redcarpet
highlighter: pygments
paginate:   5

gems:
  - jemoji
  - jekyll-sitemap

# Content Settings
logo: "/assets/images/author.jpg"
cover: "/assets/images/44a0e76eb1cf11e28bf722000a1f92f7_7.jpg"

name: 'Steven Wade'
author: 'Steven Wade'
author_image: "/assets/images/author.jpg"

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/stevenwadejr
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/stevenwadejr
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
